module.exports = {
  ACCOUNTS: 'accounts',
  USER_SECURE_DATA: 'UserSecureData',
  STORES:'stores',
  CATEGORY:'category',
  USERS:'users',
  ROLES:'roles',
  CUSTOMERS:'customers',
  MENUITEMS:'menuitems',
  TAXES:'taxes',
  POS_USERS:"pos_users",
  DISCOUNTS:"discounts",
  MODIFIERS:"modifiers",
  MODIFIERGROUP:"modifierGroups",
  SERVINGSIZE:"servingsize",
  COURSING:'coursing',
  LOGININFO:'logininfo',
  CHECKS:'checks',
  PAYMENTMETHODS:'paymentMethods',
  CLOCKINOUT:'clockinout',
  LOGS:'logs'
};
