version: 0.2
phase:
    install:
        runtime-versions:
            nodejs:18
        commands:
            - echo installing source NPM dependencies...
            - npm install --force
    build:
        commands:
            - echo Build start
            - npm run build
artifacts:
    files:
        - '**/*'
    base-directory: 'build'